### ISSUE TITLE
Cyrillic issues in Virgil font - part 2

### ISSUE THREAD

**Issue by thorn0** [excalidraw/virgil#5]
Continuation of excalidraw/excalidraw#747. Three issues.

1. This one is the most important. The uppercase Д is really wrong. It shouldn't look like the Latin uppercase G. Nobody will understand it's a Д. The original (pre-#747) glyph was fine. A Latin D-shaped glyph would be okay too (but the original one is better IMHO).

![image](https://user-images.githubusercontent.com/94334/78950941-08104f80-7ad9-11ea-981e-83c3bc60960d.png)

2. This one is about readability, pretty annoying. Pairings like гу, гі, гн, гю, etc. are hard to read because the letters collide with each other:
  ![image](https://user-images.githubusercontent.com/94334/74450471-c7a0a680-4e86-11ea-8636-41527da850b5.png)
  Possible solutions: 1) to add a bit more space after the г, or 2) to make its horizontal bar shorter. Same problem with їм and їн.

3. This one is rather a nitpick. Љ is originally a ligature Л + Ь, so it should look similar to Л in the same font, but it doesn't:
  ![image](https://user-images.githubusercontent.com/94334/74452299-907fc480-4e89-11ea-9944-caf547d7194f.png)

**Comment by lipis** [comment]
So is this solved now with: https://github.com/excalidraw/excalidraw/pull/3124

**Comment by thorn0** [comment]
My original issue - yes, it's solved. excalidraw/excalidraw#3124 seems to contain the same version of the font as here: https://github.com/Yourownfont

But these issues https://github.com/excalidraw/virgil/issues/5#issuecomment-638422510 are still present.

**Comment by thorn0** [comment]
I'm going to open separate issues for that list and close this one.
